server:
  port: 80


spring:
  application:
    name: cloud-consul-order
    #注册到consul中
  cloud:
    consul:
      host: 192.168.217.128
      port: 8500
      discovery:
        service-name: ${spring.application.name}




